# Generated by Django 5.0.6 on 2024-07-06 04:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tokobaju', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Penjualan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jumlah', models.IntegerField()),
                ('total_harga', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tanggal_penjualan', models.DateTimeField(auto_now_add=True)),
                ('produk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='penjualans', to='tokobaju.produk')),
            ],
        ),
    ]
